### ISSUE TITLE
Upgrading to 4.0.3 no file structure change

### ISSUE THREAD

**Issue by escobar5** [JustLikeIcarus/Font-Awesome-NuGet#1]
I've just upgraded the package to 4.0.3 and it has a readme that says that file locations changed and now fonts will be in application root, but I'm still getting the fonts folder inside the content folder.

I've tried uninstalling and installing it again.

**Comment by JustLikeIcarus** [comment]
The readme should say upcoming change, I apologize if the wording was off I will double check that I put it correctly.  I didn't just want to hit everyone with a different structure all of a sudden so I was going to wait a few days and either release a 4.0.3.1 update or wait for 4.0.4 from FA.  Any preference?
